# NumPy: Introduction to Numerical Python

### Installation
```bash
pip install numpy
```

In [1]:
import numpy as np

# Creating a simple array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


# Array Creation and Basic Operations

### Creating arrays
Creating arrays:

From lists, ranges, random data, or zeros/ones.

In [2]:

# Array from list
arr = np.array([10, 20, 30])

# Array of zeros
zeros = np.zeros((2, 3))

# Array of ones
ones = np.ones((3, 2))

# Range of numbers
range_arr = np.arange(0, 10, 2)

print("Array:", arr)
print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Range array:", range_arr)

Array: [10 20 30]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range array: [0 2 4 6 8]


### Basic operations:

Arithmetic is element-wise.

In [3]:
b = np.array([1, 2, 3])
c = np.array([4, 5, 6])

print("Addition:", b + c)
print("Multiplication:", b * c)
print("Exponentiation:", b ** 2)
print("Sum of elements:", np.sum(b))


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Exponentiation: [1 4 9]
Sum of elements: 6


# Indexing, Slicing, and Useful Functions
### Indexing and slicing

In [4]:
arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice [1:4]:", arr[1:4])

First element: 10
Last element: 50
Slice [1:4]: [20 30 40]


### Useful functions

In [5]:
matrix = np.array([[1, 2], [3, 4]])

print("Shape:", matrix.shape)
print("Transpose:\n", matrix.T)
print("Mean:", np.mean(matrix))
print("Max value:", np.max(matrix))

Shape: (2, 2)
Transpose:
 [[1 3]
 [2 4]]
Mean: 2.5
Max value: 4


### Bonus: Random numbers

In [6]:
random_arr = np.random.rand(3, 3)
print("Random array:\n", random_arr)

Random array:
 [[0.07972282 0.33516468 0.1184131 ]
 [0.98992152 0.54558369 0.61146266]
 [0.04344758 0.84085092 0.03707603]]
