# Deep Learning Forward Pass Example

This notebook demonstrates a toy example of a deep neural network with:
- **Input layer**: 2 neurons  
- **Hidden layer 1**: 3 neurons (ReLU)  
- **Hidden layer 2**: 2 neurons (ReLU)  
- **Output layer**: 1 neuron (Sigmoid)  
We will go through one complete forward propagation pass using toy values and both **algebraic** and **matrix-vector** calculations.


In [16]:
import numpy as np

def relu(z):
    return np.maximum(0, z)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))


In [17]:
# Input
x = np.array([[1.0], [2.0]])

In [18]:
# Weights and Biases LAYER 1 , 3 neurons, hidden layer
W1 = np.array([[1.0, 1.0],
               [0.5, 0.5],
               [1.0, -1.0]])
b1 = np.array([[0.0], [0.0], [0.0]])


In [19]:
# Weights and Biases LAYER 2 , 2 neurons, hidden layer

W2 = np.array([[0.2, 0.5, 0.3],
               [0.3, 0.1, 0.6]])
b2 = np.array([[0.1], [0.2]])

In [20]:
# Weights and Biases LAYER 3 , 1 neuron, output layer
W3 = np.array([[0.4, 0.5]])
b3 = np.array([[0.3]])

In [21]:
# Hidden Layer 1
z1 = W1 @ x + b1
a1 = relu(z1)

In [22]:
# Hidden Layer 2
z2 = W2 @ a1 + b2
a2 = relu(z2)

In [23]:
# Output Layer
z3 = W3 @ a2 + b3
y_hat = sigmoid(z3)

In [24]:
# Display all intermediate results
z1, a1, z2, a2, z3, y_hat

(array([[ 3. ],
        [ 1.5],
        [-1. ]]),
 array([[3. ],
        [1.5],
        [0. ]]),
 array([[1.45],
        [1.25]]),
 array([[1.45],
        [1.25]]),
 array([[1.505]]),
 array([[0.81831902]]))

### Final Output:
The result of the forward propagation is a single scalar prediction from the network. The final output, using sigmoid activation, lies in the range (0, 1). 

We manually chose the weights and biases such that the final output lies between **0.8 and 0.9**.
